image: testing
test:
  tags:
    - testing-docker
  script:
    - testing
  artifacts:
    paths: [report.txt.enc]
    when: always

RK_32:
    image: gcc
    stage: build
    only:
        - RK_32
    script:
         - cd RK_32_BB
         - make build

rk_03:
  image: gcc
  stage: build
  only:
    - rk_03
  script:
    - cd rk_03
    - make build
